name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Angular Github Actions
        uses: mayurrawte/github-angular-actions@latest

      - name: Test
        run: pwd && ng --help
