name: Publish
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Vue Github Actions
        uses: xRealNeon/VuePagesAction@1.0.1

      - name: Install dependency
        run: npm install
        
      - name: Build and Deploy
        run: |
          npm run build
          
          git config --global user.email "runner@github.com"
          git config --global user.name "runner"
          ng deploy --no-build --no-silent
