name: Publish
on:
  push:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Angular Github Actions
        uses: mayurrawte/github-angular-actions@latest

      - name: Install dependency
        run: npm install
        
      - name: Build and Deploy
        run: |
          ng build --localize --base-href /tools/
          cp .github/index.html dist/tools/
          git config --global user.email "runner@github.com"
          git config --global user.name "runner"
          ng deploy --no-build --no-silent
